name: Test Python files

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Test Python files
        run: |
          for file in $(find . -name "*.py"); do
            python $file
          done
